/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Cell;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.AdjustmentEvent;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Robbo13
 */
public class EditorGUI extends javax.swing.JFrame {

    private Cell selected = null;
    private int cellsize = 32;
    private boolean entfernen = false;
    private int SBx = 0;
    private int SBy = 0;
    
    public EditorGUI() {
        initComponents();
        pGraphic.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sbDown = new javax.swing.JScrollBar();
        sbRight = new javax.swing.JScrollBar();
        pGraphic = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mDatei = new javax.swing.JMenu();
        miLaden = new javax.swing.JMenuItem();
        miSpeichern = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(10, 2));
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(42, 432));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/brick.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(32, 32));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onExited(evt);
            }
        });
        jPanel2.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/tree.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(32, 32));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onExited(evt);
            }
        });
        jPanel2.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/grass.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onExited(evt);
            }
        });
        jPanel2.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setPreferredSize(new java.awt.Dimension(32, 32));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onEntfernen(evt);
            }
        });
        jPanel2.add(jLabel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        sbDown.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        sbDown.setToolTipText("");
        sbDown.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                onScrollBarValueChangedDown(evt);
            }
        });
        jPanel3.add(sbDown, java.awt.BorderLayout.PAGE_END);

        sbRight.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                onScrollBarValueChangedRight(evt);
            }
        });
        jPanel3.add(sbRight, java.awt.BorderLayout.LINE_END);

        pGraphic.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                onDragMouseOverField(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                onMoveMouseOnField(evt);
            }
        });
        pGraphic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onClickMouseOverField(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onEnteredField(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onExitedField(evt);
            }
        });
        pGraphic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(pGraphic, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        mDatei.setText("File");

        miLaden.setText("Load");
        miLaden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoad(evt);
            }
        });
        mDatei.add(miLaden);

        miSpeichern.setText("Save");
        miSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSave(evt);
            }
        });
        mDatei.add(miSpeichern);

        jMenuBar1.add(mDatei);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSave
        
    }//GEN-LAST:event_onSave

    private void onLoad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLoad
        
    }//GEN-LAST:event_onLoad

    private void onClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClicked
        selected = new Cell(((JLabel)evt.getSource()).getIcon());
        selected.setSize(cellsize, cellsize);
        System.out.println("Label selected!");
    }//GEN-LAST:event_onClicked

    private void onEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onEntered
        JLabel label = (JLabel)evt.getSource();
        label.setBorder(new LineBorder(Color.yellow));
    }//GEN-LAST:event_onEntered

    private void onExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onExited
        JLabel label = (JLabel)evt.getSource();
        label.setBorder(null);
    }//GEN-LAST:event_onExited

    private void onEnteredField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onEnteredField
        if(selected != null){
            pGraphic.add(selected);
            this.updateGraphicPanel();
        }
    }//GEN-LAST:event_onEnteredField

    private void onExitedField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onExitedField
        if(selected != null){
            pGraphic.remove(selected);
            this.updateGraphicPanel();
        }
    }//GEN-LAST:event_onExitedField

    private void onMoveMouseOnField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMoveMouseOnField
        if(selected != null){
            int currentCellX = evt.getX()/cellsize;
            int currentCellY = evt.getY()/cellsize;
            selected.setLocation(currentCellX*cellsize,currentCellY*cellsize);
            this.updateGraphicPanel();
        }
    }//GEN-LAST:event_onMoveMouseOnField

    private void onScrollBarValueChangedDown(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_onScrollBarValueChangedDown
        for (Component comp : pGraphic.getComponents()) {
            if(evt.getValueIsAdjusting()){
                comp.setLocation(comp.getX() - (sbDown.getValue() - SBx)*5,comp.getY());
                SBx = sbDown.getValue();
                this.updateGraphicPanel();
            }
        }
    }//GEN-LAST:event_onScrollBarValueChangedDown

    private void onScrollBarValueChangedRight(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_onScrollBarValueChangedRight
        for (Component comp : pGraphic.getComponents()) {
            if(evt.getValueIsAdjusting()){
                comp.setLocation(comp.getX(),comp.getY() - (sbRight.getValue() - SBy)*5);
                SBy = sbRight.getValue();
                this.updateGraphicPanel();
            }
        }
    }//GEN-LAST:event_onScrollBarValueChangedRight

    private void onClickMouseOverField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onClickMouseOverField
        if(selected != null){
            if(!selected.isAlreadyThere(pGraphic)){
                Cell cell = new Cell(selected.getIcon());
                cell.setPlaced(true);
                cell.setVisible(true);
                cell.setSize(cellsize,cellsize);
                cell.setLocation(selected.getX(),selected.getY());
                pGraphic.add(cell);
                this.updateGraphicPanel();
                System.out.println("Yayja");
            }
        }
    }//GEN-LAST:event_onClickMouseOverField

    private void onEntfernen(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onEntfernen
        entfernen = true;
    }//GEN-LAST:event_onEntfernen

    private void onDragMouseOverField(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onDragMouseOverField
        if(selected != null){
            int currentCellX = evt.getX()/cellsize;
            int currentCellY = evt.getY()/cellsize;
            selected.setLocation(currentCellX*cellsize,currentCellY*cellsize);
            if(!selected.isAlreadyThere(pGraphic)){
                Cell cell = new Cell(selected.getIcon());
                cell.setPlaced(true);
                cell.setVisible(true);
                cell.setSize(cellsize,cellsize);
                cell.setLocation(selected.getX(),selected.getY());
                pGraphic.add(cell);
                this.updateGraphicPanel();
                System.out.println("Yayja");
            }
        }
    }//GEN-LAST:event_onDragMouseOverField

    
    public void updateGraphicPanel(){
        /*for (Object obj : pGraphic.getComponents()) {
            Component comp = (Component)obj;
        }*/
        pGraphic.updateUI();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu mDatei;
    private javax.swing.JMenuItem miLaden;
    private javax.swing.JMenuItem miSpeichern;
    private javax.swing.JPanel pGraphic;
    private javax.swing.JScrollBar sbDown;
    private javax.swing.JScrollBar sbRight;
    // End of variables declaration//GEN-END:variables
}
